version: "3"

services:
  pg14:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    container_name: pg14

volumes:
  pgdata:
